services:
  desafio-btg-pactual:
    container_name: desafio-btg-pactual
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
    networks:
      - desafio-btg-pactual
    tty: true
    stdin_open: true
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - desafio-btg-pactual
  mongo:
    image: mongo:8.0.8
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - desafio-btg-pactual
  mongoexpress:
    image: mongo-express
    container_name: mongodb_express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: secret
      ME_CONFIG_MONGODB_PORT: 27017
    networks:
      - desafio-btg-pactual
networks: 
    desafio-btg-pactual:
      driver: bridge
